# Generated by Django 6.1 on 2026-09-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_schoolsetting_studentprofile_graderecord_feeledger_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsetting',
            name='logo_url',
            field=models.CharField(default='/media/branding/logo.png', max_length=500),
        ),
    ]
